### ISSUE TITLE
Implement new config spec

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#449]
changes required to helix-cli based from discussion in https://github.com/adobe/helix-shared/pull/12:

- [x] `hlx up` uses a built-in default config and issues a warning if no config is present
- [x] `hlx up` provides an option to simulate a domain with `--domain` (moved to #108)
- [x] `hlx deploy` fails if no config is present (with an informative error)
- [x] `hlx deploy` lists all strains affected
- [x] `hlx deploy` suggests new strains if non affected
- [x] `hlx deploy` adds missing stain with `--add` (moved to #456)
- [x] `hlx deploy` uses _new_ action name format
- [x] `hlx deploy` writes correct effective config based on resolved actions (moved to #457)
- [x] `hlx publish` can deal with new code format
- [x] `hlx perf` can deal with config
- [x] `hlx deploy` updates the `package` property and writes back the `helix-config.yaml`
- [x] `hlx publish` updates the strains that contain a `package` property
- [x] update demos with correct config
