### ISSUE TITLE
Harmonize `context.request` and `action.request`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#531]
**Description**
As mentioned in https://github.com/adobe/helix-pipeline/issues/170, the `context.request.path` is misleading. Therefor this will be hamronized such as `context.request` will only contain client request values, and `action.request.params` will contain resource values:

| property | value | comment |
|----------|------|-----------|
| `context.request.url` | `/docs/api/general/index.html?a=1` | the original client request url |
| `context.request.path` | `/docs/api/general/index.html` | the original request path |
| `action.request.params.path` | `/general/index.md` | the _resource_ path |
| `action.request.params.rootPath` | `/docs/api` | The mount root |

> **NOTE** This is a backward incompatible change. Projects using `request.path` in the HTL or `payload.request.path` in the `pre.js` will need to use `action.request.params.path` instead.

Tasks:
- [x] update helix-pipeline to include the new/corrected properties
- [x] update helix-cli to pass along the `rootPath` https://github.com/adobe/helix-pipeline/issues/170
- [x] update helix-simulator to pass along to `rootPath` https://github.com/adobe/helix-simulator/issues/137
- [x] update helix-publish with _this_ changes as well https://github.com/adobe/helix-publish/issues/11
